### ISSUE TITLE
Static version

### ISSUE THREAD

**Issue by grylem** [donmccaughey/xz_pkg#2]
Hi,
now xz compiled with a liblzma.5.dylib maybe you can also make a static version without dependence on liblzma.5.dylib?
Regards.

**Comment by donmccaughey** [comment]
I created [rev 2](https://github.com/donmccaughey/xz_pkg/releases/tag/v5.2.5-r2) of the installer package `xz-5.2.5-r2.pkg`, which statically links all the executables to `liblzma.a`.  The `liblzma` dylib is still included, but not needed to run `xz`.  Enjoy!
